USE [master]
GO
/****** Object:  Database [APQM_DB]    Script Date: 08/14/2013 15:36:01 ******/
CREATE DATABASE [APQM_DB] ON  PRIMARY 
( NAME = N'APQM_DB', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\APQM_DB.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'APQM_DB_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\APQM_DB_log.ldf' , SIZE = 6144KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'APQM_DB', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [APQM_DB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [APQM_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [APQM_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [APQM_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [APQM_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [APQM_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [APQM_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [APQM_DB] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [APQM_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [APQM_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [APQM_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [APQM_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [APQM_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [APQM_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [APQM_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [APQM_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [APQM_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [APQM_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [APQM_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [APQM_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [APQM_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [APQM_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [APQM_DB] SET  READ_WRITE 
GO
ALTER DATABASE [APQM_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [APQM_DB] SET  MULTI_USER 
GO
ALTER DATABASE [APQM_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [APQM_DB] SET DB_CHAINING OFF 